# GitHub Sponsors configuration
# This file enables the "Sponsor" button on the repository

github: # Add your GitHub username here for GitHub Sponsors
# patreon: # Add your Patreon username
# open_collective: # Add your Open Collective username
# ko_fi: # Add your Ko-fi username
# tidelift: # Add your Tidelift platform/package name
# community_bridge: # Add your Community Bridge project name
# liberapay: # Add your Liberapay username
# issuehunt: # Add your IssueHunt username
# custom: # Add your custom sponsorship URLs (max 4)
